name: Terraform

on:
  workflow_dispatch:
  push:
    branches: ["main", "task-1"]
  pull_request:
    branches: ["main", "task-1"]

permissions:
  id-token: write
  contents: read 

jobs:
  setup:
    uses: ./.github/workflows/aws-setup.yml

  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Check
        run: terraform fmt -check ./terraform

  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Initialize terraform
        run: terraform init -chdir=./terraform
      - name: Run plan
        run: terraform plan -chdir=./terraform
