name: aws-setup

on:
  workflow_call:
    outputs:
      role-ready:
        value: ${{ jobs.aws-setup.outputs.role-ready }}

permissions:
  id-token: write      # needed for OIDC-based AWS auth
  contents: read       # needed for actions/checkout or reading the repo

jobs:
  aws-setup:
    runs-on: ubuntu-latest
    outputs:
      role-ready: ${{ steps.set-output.outputs.ready }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::747639505707:role/GithubActionsRole
          aws-region: eu-central-1

      - name: Set output (optional)
        id: set-output
        run: echo "ready=true" >> "$GITHUB_OUTPUT"